services:
  main: 
    image: ubuntu:noble
    command: bash /app/iso_modifier.sh
    working_dir: /app
    privileged: true # Un peu sus mais tkt
    volumes: 
      - type: bind
        source: ./iso
        target: /app/iso
      - type: bind
        source: ./iso_modifier.sh
        target: /app/iso_modifier.sh
      - type: bind
        source: ./autoinstall.yaml
        target: /app/autoinstall.yaml
      - type: bind
        source: ./scripts
        target: /app/scripts
      - type: bind
        source: ./assets
        target: /app/assets
      - type: bind
        source: ./desktop_files
        target: /app/desktop_files
      - type: bind
        source: ./new_iso
        target: /app/new_iso
